apiVersion: kubedb.com/v1alpha1
kind: Etcd
metadata:
  name: etcdb-wipe
  namespace: demo
spec:
  replicas: 3
  version: "3.2.13"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: wipeOut
  monitor:
    agent: prometheus.io/builtin
