apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: snapshot-etcd
  namespace: demo
  labels:
    kubedb.com/kind: Etcd
spec:
  databaseName: etcdb
  storageSecretName: gcs-secret
  gcs:
    bucket: kubedb
    prefix: etcdb-demo
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
