apiVersion: kubedb.com/v1alpha1
kind: Etcd
metadata:
  name: etcdbx
  namespace: test
spec:
  replicas: 1
  version: "3.2.13"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
