apiVersion: kubedb.com/v1alpha1
kind: Etcd
metadata:
  name: etcdb
  namespace: demo
spec:
  replicas: 3
  version: "3.3.9"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
