apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: snapshot-xyz
  namespace: test
  labels:
    kubedb.com/kind: Etcd
spec:
  databaseName: etcdbx
  storageSecretName: gcs-secret
  gcs:
    bucket: kubedbetcd
    prefix: etcdb
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
